let nombre = "Alejandrina";
let apellido = "Porrini"; 
let edad = 34; 
let numeroTelefono = "0303-456";
let socio = false;
let fechaPartido = "31/10/2024";
let horaPartido = "10:45";
let numeroSilla = 23;
let precioBoleto = 10000;

console.log("Nombre: ", nombre);
console.log("Apellido: ", apellido);
console.log("Edad: ", edad);
console.log("Número de Teléfono: ", numeroTelefono);
console.log("Es socio: ", socio);
console.log("La fecha del partido es: ", fechaPartido);
console.log("Fecha del Partido: ", fechaPartido);
console.log("Hora del Partido: ", horaPartido);
console.log("Número de Silla: ", numeroSilla);
console.log("Precio del Boleto: ", precioBoleto);

console.log("Tipo de dato de nombre:", typeof nombre);
console.log("Tipo de dato de apellido:", typeof apellido);
console.log("Tipo de dato de edad:", typeof edad);
console.log("Tipo de dato de número de teléfono:", typeof numeroTelefono);
console.log("Tipo de dato de socio:", typeof socio);
console.log("Tipo de dato de fecha del partido:", typeof fechaPartido);
console.log("Tipo de dato de hora del partido:", typeof horaPartido);
console.log("Tipo de dato de número de silla:", typeof numeroSilla);
console.log("Tipo de dato de precio del boleto:", typeof precioBoleto);